name: Popeye

services: 
  poll:
    build:
      context: poll
      dockerfile: Dockerfile
    ports:
     -  5000:80
    environment:
      REDIS_HOST: redis
      REDIS_PASSWORD: cynthiapass
    healthcheck:
      test: curl --fail http://localhost:5000:80/ || exit 1
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - poll-tier
  
  redis:
    image: redis:7 
    ports:
      - 6379
    environment:
      REDIS_PASSWORD: cynthiapass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - poll-tier
      - back-tier
  
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    environment:
      REDIS_HOST: redis
      REDIS_PASSWORD: cynthiapass
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - back-tier
    depends_on:
      - redis
      - db
  
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - result-tier
      - back-tier
  
  result:
    build:
      context: result
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - result-tier
    healthcheck:
      test: curl --fail http://localhost:5001:80/ || exit 1
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    depends_on:
      - db
  
networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data:
    driver: local
